/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer */

#ifndef _Included_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
#define _Included_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
#ifdef __cplusplus
extern "C" {
#endif
#undef net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_zoom_level
#define net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_zoom_level 13L
/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    drawNativeCall
 * Signature: ([II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_drawNativeCall
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
