/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer */

#ifndef _Included_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
#define _Included_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
#ifdef __cplusplus
extern "C" {
#endif
#undef net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_zoom_level
#define net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_zoom_level 13L
/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    drawCairoCall
 * Signature: ([IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_drawCairoCall
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    initOpenGLRenderer
 * Signature: (II[II[II[II)V
 */
JNIEXPORT void JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_initOpenGLRenderer
  (JNIEnv *, jobject, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint);

/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    drawOpenGLCall
 * Signature: ([IIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_drawOpenGLCall
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint);

/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    closeOpenGLRenderer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_closeOpenGLRenderer
  (JNIEnv *, jobject);

/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    updateOpenGLDistances
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_updateOpenGLDistances
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer
 * Method:    drawOpenGLTile
 * Signature: (IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_zettroke_PropertyHeatMapServer_utils_RoadGraphDrawer_drawOpenGLTile
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
